### ISSUE TITLE
Cannot register on windows 2008 r2 64-bit

### ISSUE THREAD

**Issue by hwfy** [tablacus/TablacusScriptControl#21]
The following error occurred when I registered the script as an administrator：

1. Access is denied.
2. The module 'tsc64.dll' was loaded but the call to DllRegisterServer failed with error code 0x80070005.

First of all I run as an administrator, and secondly I have installed Microsoft Visual C++ 2010 x64 Redistributable, it is okay to try to register other components

Thanks.

**Comment by tablacus** [comment]
How did you try to install?
e.g. execute setup.exe / rundll32 tsc64.dll

Regards,

**Comment by hwfy** [comment]
Your way can

Thanks.
