### ISSUE TITLE
AddObject and AddCode methods in Tablacus Script Control have some problems and they gives "redefined" error.

### ISSUE THREAD

**Issue by turgay06** [tablacus/TablacusScriptControl#6]
Sample code is below:
Error: undo is redefined.

[ComVisible(true)]
public class TestClass
{
       public string Undo { get; set; }
}

string progID = "Tablacus.ScriptControl";
Type oType = Type.GetTypeFromProgID(progID);
if (oType != null)
{
	try
	{
		System.Text.StringBuilder sbCode = new System.Text.StringBuilder();
		sbCode.Append("Sub Main\n\r");
		sbCode.Append("With TestObject" + Environment.NewLine);
		sbCode.Append("MsgBox \"Hello World\"\n\r");
		sbCode.Append("End With" + Environment.NewLine);
		sbCode.Append("End Sub");
		string content = sbCode.ToString();

		object testObj = new TestClass();

		object objTablacus = Activator.CreateInstance(oType);
		objTablacus.GetType().InvokeMember("Language", BindingFlags.InvokeMethod, null, objTablacus, new object[] { "VBScript" });
		objTablacus.GetType().InvokeMember("AddObject", BindingFlags.InvokeMethod, null, objTablacus, new object[] { "TestObject", testObj, false });
		objTablacus.GetType().InvokeMember("AddCode", BindingFlags.InvokeMethod, null, objTablacus, new object[] { content });
		objTablacus.GetType().InvokeMember("AddCode", BindingFlags.InvokeMethod, null, objTablacus, new object[] { "const undo = 0" }); //Gives error-> undo redefined

		object runResult = objTablacus.GetType().InvokeMember("Run", BindingFlags.InvokeMethod, null, objTablacus, new object[] { "Main" });

		object error = objTablacus.GetType().InvokeMember("Error", BindingFlags.InvokeMethod, null, objTablacus, new object[] { });
		if (error != null)
		{
			Type errorType = error.GetType();
			object errorDesc = errorType.InvokeMember("Description", BindingFlags.InvokeMethod, null, error, new object[] { });
			object errorLine = errorType.InvokeMember("Line", BindingFlags.InvokeMethod, null, error, new object[] { });
			object errorColumn = errorType.InvokeMember("Column", BindingFlags.InvokeMethod, null, error, new object[] { });
			object errorSource = errorType.InvokeMember("Source", BindingFlags.InvokeMethod, null, error, new object[] { });
		}
	}
	catch (Exception ex)
	{
		
	}
}

**Comment by tablacus** [comment]
I created a test program with JavaScript.
It's not a problem.
C# related?
I do not have time to install C # now, Could you please wait for a while?
Best regards,
```
var progID = "Tablacus.ScriptControl";
var testObj = {hello: "Hello World"};
var sbCode = [];
sbCode.push("Sub Main");
sbCode.push("With TestObject");
sbCode.push("MsgBox hello");
sbCode.push("End With");
sbCode.push("End Sub");
var content = sbCode.join("\r\n");

var objTablacus = new ActiveXObject(progID);
objTablacus.Language = "VBScript";
objTablacus.AddObject("TestObject", testObj, true);
objTablacus.AddCode(content);
objTablacus.AddCode("const undo = 0"); //Gives error-> undo redefined
objTablacus.AddCode("MsgBox undo");

var runResult = objTablacus.Run("Main");

var error = objTablacus.Error;
if (error) {
	var errorDesc = error.Description;
	var errorLine = error.Line;
	var errorColumn = error.Column;
	var errorSource = error.Source;
}

```

**Comment by turgay06** [comment]
You can test by changing following line in your code.

objTablacus.AddCode("const undo = 0"); -> objTablacus.AddCode("const hello = 0");

Also I have no error when I test the code using MSScriptControl class.

Thanks

**Comment by tablacus** [comment]
I've adjusted AddObject in TSC 1.0.5.0.
Please update it.
Best regards,

**Comment by turgay06** [comment]
Thanks

**Comment by tablacus** [comment]
My pleasure.
