### ISSUE TITLE
Error when using Run() function

### ISSUE THREAD

**Issue by KodaPOwER** [tablacus/TablacusScriptControl#8]
Hello,

I'm using you control as 64-bit MSScript Control replacement inside an ASP.NET WebForm WebApplication.

I can get it works, but it gives an error when i call the Run() function.

That's an example of code that give error:
```
Dim oScript = New MSScriptControl.ScriptControl
oScript.Language = "vbscript"
oScript.AllowUI = False
oScript.Reset()
Dim db = New clsData
Dim oi = New clsOI(db)
oScript.AddObject("oi", oi) ' AGGIUNTO PER ESEGUIRE FUNZIONI
Try
    oScript.AddCode(
    "Function runFormula()" & vbCrLf &
    "retValue = 10" & vbCrLf &
    "runFormula=retValue" + vbCrLf &
    "end function")
    oScript.ExecuteStatement("runFormula()")
    Dim returned = oScript.Eval("runFormula()")
    Dim retValue = oScript.Run("runFormula")
Catch ex As Exception
    Dim errorMessage = oScript.Error.Text
    Throw
End Try
```

This is the exception thrown:
Exception thrown at 0x00007FFFDC921AC8 (tsc64.dll) in iisexpress.exe: 0xC0000005: Access violation reading location 0x0000000000000000.

Running it on IISExpress 64 bit with project compiled for x64 cpu.

If i run it in 32-bit with the original microsoft control it work.

Can you help me?
Thanks!

**Comment by tablacus** [comment]
There was a problem with Reset.
TSC64 1.0.6.0 released.
Please update.

Thank you,

**Comment by KodaPOwER** [comment]
I will update and report back the results.
Thank you,

**Comment by KodaPOwER** [comment]
Yep, now it seems to work like a charm! 
Thank you for your effort and for this precious library that permit us to switch our web app to x64 architecture!

**Comment by tablacus** [comment]
My pleasure,
